In [9]:
import numpy as np

In [6]:
a=np.array([1,2,3])
a

array([1, 2, 3])

In [7]:
type(a)

numpy.ndarray

In [8]:
a.ndim

1

In [10]:
a.shape

(3,)

In [11]:
b=np.array([[1,2,3],[4,5,6]])
b

array([[1, 2, 3],
       [4, 5, 6]])

In [12]:
type(b)

numpy.ndarray

In [13]:
b.ndim

2

In [14]:
b.shape

(2, 3)

In [15]:
b.dtype

dtype('int32')

# Matrix creation

In [16]:
arr=np.zeros(5)
arr

array([0., 0., 0., 0., 0.])

In [17]:
arr.dtype

dtype('float64')

In [20]:
arr1=np.zeros((5), dtype=int)

In [21]:
arr1

array([0, 0, 0, 0, 0])

In [22]:
arr1.dtype

dtype('int32')

In [23]:
arr=np.zeros((2,3))
arr

array([[0., 0., 0.],
       [0., 0., 0.]])

# np.ones

In [16]:
import numpy as np

In [18]:
arr=np.ones(5)
print(arr)

[1. 1. 1. 1. 1.]


In [19]:
arr=np.ones((3,3))
print(arr)

[[1. 1. 1.]
 [1. 1. 1.]
 [1. 1. 1.]]


In [20]:
print(1+np.ones((3,3)))


[[2. 2. 2.]
 [2. 2. 2.]
 [2. 2. 2.]]


# np.eye

In [21]:
import numpy as np

In [22]:
arr=np.eye((2),dtype=int)
print(arr)

[[1 0]
 [0 1]]


In [23]:
arr=np.eye((3),dtype=int)
print(arr)
print(arr.shape)


[[1 0 0]
 [0 1 0]
 [0 0 1]]
(3, 3)


# np.diag

In [24]:
import numpy as np

In [25]:
arr=np.diag([1,2,3])
arr

array([[1, 0, 0],
       [0, 2, 0],
       [0, 0, 3]])

In [26]:
arr=np.diag([1,2,3])
arr

array([[1, 0, 0],
       [0, 2, 0],
       [0, 0, 3]])

# Generate Random Float

In [27]:
import numpy as np

In [28]:
r=np.random.rand(2,2)#Random number generation (from Uniform distribution from 0 to 1
r


array([[0.33843631, 0.8146199 ],
       [0.1808775 , 0.80389417]])

In [29]:
#Random number generation from Normal distribution with zero mean and standard deviation 1 i.e. standard normal")
r=np.random.randn(2,2)
r

array([[ 0.60428837,  0.2400986 ],
       [-0.02575397, -0.15817842]])

# Generate Random Array

In [30]:
import numpy as np

In [31]:
rand_arr=np.random.randint(10,size=(5))
rand_arr


array([1, 8, 7, 5, 1])

In [32]:
rand_arr=np.random.randint(10,size=(2,3))
rand_arr

array([[9, 0, 6],
       [9, 8, 3]])

In [33]:
rand_arr=np.random.rand(5)
rand_arr


array([0.34122426, 0.80077279, 0.18775363, 0.29233957, 0.45848661])

In [34]:
min=10
max=20
rand_arr=min+((max-min)*np.random.rand())
print(rand_arr)


13.97001240265531


# reshaping

In [35]:
arr=np.random.randint(1,50,10)
arr

array([36, 37,  4, 20, 46, 11, 40, 15, 43, 16])

In [36]:
arr.shape

(10,)

In [37]:
arr=arr.reshape(2,5)
arr

array([[36, 37,  4, 20, 46],
       [11, 40, 15, 43, 16]])

In [38]:
arr.shape


(2, 5)

# arrange

In [39]:
import numpy as np

In [40]:
np.arange(1,10,2)

array([1, 3, 5, 7, 9])

In [41]:
np.arange(1,10,3)

array([1, 4, 7])

In [42]:
list(range(1,10,2))

[1, 3, 5, 7, 9]

In [43]:
np.arange(10,0,-1)

array([10,  9,  8,  7,  6,  5,  4,  3,  2,  1])

# Assigning value

In [44]:
import numpy as np 

In [45]:
arr=np.diag([1,2,3])
arr

array([[1, 0, 0],
       [0, 2, 0],
       [0, 0, 3]])

In [46]:
arr[2,1]=4
arr

array([[1, 0, 0],
       [0, 2, 0],
       [0, 4, 3]])

# slicing

In [47]:
import numpy as np

In [48]:
a=np.arange(10,20)
a

array([10, 11, 12, 13, 14, 15, 16, 17, 18, 19])

In [49]:
a[1:8:2] 

array([11, 13, 15, 17])

In [50]:
a[[0,2,4]] 

array([10, 12, 14])

In [51]:
a=np.arange(10)

In [52]:
b=np.arange(5)
a[5:]=b[::-1]
a

array([0, 1, 2, 3, 4, 4, 3, 2, 1, 0])

In [53]:
a=np.arange(10)
print(a)
b=a[::2]
print(b)

[0 1 2 3 4 5 6 7 8 9]
[0 2 4 6 8]


In [54]:
b[0]=10
b

array([10,  2,  4,  6,  8])

In [55]:
a

array([10,  1,  2,  3,  4,  5,  6,  7,  8,  9])

In [56]:
np.shares_memory(a,b) 

True

In [57]:
a=np.arange(10)
c=a[::2].copy()
c


array([0, 2, 4, 6, 8])

In [58]:
np.shares_memory(a,c)

False

# operation on numpy

In [59]:
import numpy as np